Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/signaturit_client.rb
    - test/test_signaturit_client.rb

Metrics/MethodLength:
  Max: 20

Naming/AccessorMethodName:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

